// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect } from "jsr:@std/expect"
import { pipe } from '@jvlk/fp-tsm/function'

Deno.test('Example 1', () => {
  const len = (s: string): number => s.length
  const double = (n: number): number => n * 2
  expect(double(len('aaa'))).toBe(6)
  expect(pipe('aaa', len, double)).toBe(6)
})
