// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect } from 'jsr:@std/expect'
import { Option } from '@jvlk/fp-tsm'

Deno.test('Example 1', () => {
  expect(Option.of(undefined)).toEqual({ _tag: 'None' })
  expect(Option.of(null)).toEqual({ _tag: 'None' })
  expect(Option.of(1)).toEqual({ _tag: 'Some', value: 1 })
})

Deno.test('Example 2', () => {
  expect(Option.none).toEqual({ _tag: 'None' })
})

Deno.test('Example 3', () => {
  expect(Option.some(1)).toEqual({ _tag: 'Some', value: 1 })
  expect(Option.some('hello')).toEqual({ _tag: 'Some', value: 'hello' })
})

Deno.test('Example 4', () => {
  const isPositive = Option.fromPredicate((n: number) => n >= 0)
  expect(isPositive(-1)).toEqual(Option.none)
  expect(isPositive(1)).toEqual(Option.some(1))
})
