// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import * as Option from '@jvlk/fp-tsm/Option'
import { expect } from 'jsr:@std/expect'

Deno.test('Example 1', () => {
  expect(Option.of(undefined)).toEqual({ _tag: 'None' })
  expect(Option.of(null)).toEqual({ _tag: 'None' })
  expect(Option.of(1)).toEqual({ _tag: 'Some', value: 1 })
})
