name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Generate example tests
        run: deno task tests:generate
      - name: Test
        run: deno test
      - name: Lint
        run: deno lint src
      - name: Check
        run: deno check --doc src/**/*.ts

