name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
  ci:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: deno test
      - name: Lint
        run: deno lint src
      - name: Check
        run: deno check --doc src

